print ("Inteiro")
print int(1.0)
print ("Inteiro")
print int('9')
print ("Ponto flutuante")
print float(1)
print ("Ponto flutuante")
print float('9.2')
print ("Ponto flutuante")
print float('-inf')
print ("Ponto flutuante")
print float('+inf')
print ("Ponto flutuante")
print float('nan')
print ("Numero complexo")
print complex(1,2)
